# Generated by Django 5.0.7 on 2024-08-07 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngredientsInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemName", models.CharField(max_length=30)),
                ("itemPrice", models.FloatField(default=0.0)),
                ("quantity", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameCategory", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menuItemName", models.CharField(max_length=30)),
                ("menuItemDescription", models.CharField(max_length=60)),
                ("menuItemPrice", models.FloatField(default=0.0)),
                ("menuCategory", models.CharField(max_length=55)),
                ("imageUrl", models.URLField(blank=True, max_length=255, null=True)),
                ("recipeUrl", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "menuItemCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.menuitemcategory",
                        verbose_name="Itemm Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseTimeInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchaseTime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "menu_item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.menuitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeRequirementInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredientQuantity", models.FloatField(default=0.0)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ingredientsinventory",
                        verbose_name="Ingredients",
                    ),
                ),
                (
                    "menuItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.menuitem",
                        verbose_name="Menu Itemss",
                    ),
                ),
            ],
        ),
    ]
